version: '3.8'

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - AUTH_KEY=${AUTH_KEY}
      - SERVER_PORT=${SERVER_PORT}
    restart: always

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432" 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
     - ./migrations:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: redis:7-alpine

    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data: